version: '3.9'

services:
  pg_db:
    image: postgres:17
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    # set port after starting DB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      pg_db:
        condition: service_healthy

#    environment:
#      DB_HOST: pg_db
#      DB_PORT: 5433
#      DB_NAME: test_db
#      DB_USER: test_user
#      DB_PASSWORD: test_password # ${MY_SECRET_KEY} як альтернатива дадоати пароль в env vars